--- 
- 
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
  # added comment

      - name: Get recusb repo from GitHub
        git: 
          dest: /home/pi/git_scratch
          repo: "https://github.com/Wied58/recusb.git"
          update: yes
          force: yes
          version: "main"

      - name: Change directory? owership and permissions
        file:
           path: /home/pi/Tools/git_scratch
           state: directory
           owner: pi 
           group: pi
           # when specifying mode using octal numbers, add a leading 0
           mode: 0755
           recurse: yes

      - name: Copy recusb from git_repo to sendusb
        copy:
          src: /home/pi/Tools/git_scratch/
          dest: /home/pi/recusb/
          owner: pi
          group: pi
          mode: 0775
